vfh_node:
  ros__parameters:
    golbal_frame: "map"
    robot_frame: "base_footprint"
    robot_bubble: 35.0

    max_velocity: 0.25
    min_velocity: 0.0
    max_yawrate: 0.25

    dist_goal_th_: 0.1
    angle_goal_th: 0.1
    obstacle_th: 1.0
    emergency_th: 0.51

    sub_goal_th: 1.75
    safety_distance: 2.5

    goal_point_x: 1.0
    goal_point_y: -2.0
    goal_point_yaw: 0.0
